# Generated by Django 5.2.7 on 2025-10-09 12:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(default='count', max_length=20)),
                ('tags', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'services_system_metrics',
                'indexes': [models.Index(fields=['metric_name', 'timestamp'], name='services_sy_metric__8b021d_idx'), models.Index(fields=['timestamp', 'metric_name'], name='services_sy_timesta_d34d3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIProcessingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operation_type', models.CharField(db_index=True, max_length=100)),
                ('content_type', models.CharField(max_length=50)),
                ('processing_time', models.FloatField()),
                ('input_size', models.IntegerField()),
                ('output_size', models.IntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('api_calls_made', models.IntegerField(default=1)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_ai_processing_metrics',
                'indexes': [models.Index(fields=['operation_type', 'timestamp'], name='services_ai_operati_7db4dc_idx'), models.Index(fields=['success', 'timestamp'], name='services_ai_success_882f34_idx'), models.Index(fields=['user', 'timestamp'], name='services_ai_user_id_963c63_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('alert_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_alert_log',
                'indexes': [models.Index(fields=['status', 'severity', 'timestamp'], name='services_al_status_9426cb_idx'), models.Index(fields=['alert_type', 'timestamp'], name='services_al_alert_t_686382_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_type', models.CharField(db_index=True, max_length=200)),
                ('error_message', models.TextField()),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('stack_trace', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_error_log',
                'indexes': [models.Index(fields=['timestamp', 'error_type'], name='services_er_timesta_4cb77c_idx'), models.Index(fields=['resolved', 'timestamp'], name='services_er_resolve_099d03_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('operation', models.CharField(db_index=True, max_length=200)),
                ('duration', models.FloatField()),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_performance_log',
                'indexes': [models.Index(fields=['timestamp', 'operation'], name='services_pe_timesta_0edbe1_idx'), models.Index(fields=['operation', 'duration'], name='services_pe_operati_12fb96_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('activity_type', models.CharField(db_index=True, max_length=100)),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services_user_activity_log',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='services_us_user_id_875e18_idx'), models.Index(fields=['activity_type', 'timestamp'], name='services_us_activit_778ae5_idx'), models.Index(fields=['timestamp', 'user'], name='services_us_timesta_ee1413_idx')],
            },
        ),
    ]
