# Generated by Django 5.2.7 on 2025-10-09 05:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_studentprofile_leaderboard_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the academic subject', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the subject')),
                ('category', models.CharField(blank=True, help_text='Subject category (e.g., STEM, Humanities, Languages)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', help_text='Current status of the partnership', max_length=15)),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of study sessions completed together', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student1', models.ForeignKey(help_text='First student in the partnership', on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_student1', to='accounts.studentprofile')),
                ('student2', models.ForeignKey(help_text='Second student in the partnership', on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_student2', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(help_text='Subject for study partnership', on_delete=django.db.models.deletion.CASCADE, to='community.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student1', 'student2', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled date and time for the study session')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration of the session in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('topic', models.CharField(blank=True, help_text='Specific topic or focus for the session', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', help_text='Current status of the session', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Notes or agenda for the session')),
                ('session_summary', models.TextField(blank=True, help_text='Summary of what was covered in the session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Student who created this session', on_delete=django.db.models.deletion.CASCADE, related_name='created_study_sessions', to='accounts.studentprofile')),
                ('partnership', models.ForeignKey(help_text='The partnership this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='community.studypartnership')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text="Tutor's professional biography and teaching approach")),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-2 years)'), ('intermediate', 'Intermediate (3-5 years)'), ('experienced', 'Experienced (6-10 years)'), ('expert', 'Expert (10+ years)')], help_text="Tutor's experience level", max_length=15)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate in USD', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('5.00'))])),
                ('rating', models.FloatField(default=0.0, help_text='Average rating from student reviews', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of reviews received', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of tutoring sessions completed', validators=[django.core.validators.MinValueValidator(0)])),
                ('languages', models.JSONField(default=list, help_text='Languages the tutor can teach in')),
                ('timezone', models.CharField(default='UTC', help_text="Tutor's timezone for scheduling", max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval'), ('suspended', 'Suspended')], default='pending', help_text='Current status of the tutor profile', max_length=15)),
                ('verified', models.BooleanField(default=False, help_text="Whether the tutor's credentials have been verified")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(help_text='Subjects the tutor can teach', related_name='tutors', to='community.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-total_sessions'],
            },
        ),
        migrations.CreateModel(
            name='TutorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled date and time for the session')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duration of the session in minutes', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', help_text='Current status of the booking', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements for the session')),
                ('session_notes', models.TextField(blank=True, help_text='Notes from the completed session')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost for the session', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_bookings', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(help_text='Subject for the tutoring session', on_delete=django.db.models.deletion.CASCADE, to='community.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='community.tutorprofile')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='StudyPartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Optional message from requester')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the request', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested', models.ForeignKey(help_text='Student who received the partner request', on_delete=django.db.models.deletion.CASCADE, related_name='received_partner_requests', to='accounts.studentprofile')),
                ('requester', models.ForeignKey(help_text='Student who sent the partner request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_partner_requests', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(help_text='Subject for study partnership', on_delete=django.db.models.deletion.CASCADE, to='community.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'requested', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Start time of availability slot')),
                ('end_time', models.TimeField(help_text='End time of availability slot')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this slot is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='community.tutorprofile')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('tutor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TutorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Written review comment')),
                ('would_recommend', models.BooleanField(default=True, help_text='Whether the student would recommend this tutor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='The booking this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='community.tutorbooking')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reviews', to='accounts.studentprofile')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='community.tutorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tutor', 'student', 'booking')},
            },
        ),
    ]
