# Generated by Django 5.2.7 on 2025-10-09 06:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_leaderboard_visible_and_more'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='notes',
        ),
        migrations.AddField(
            model_name='studysession',
            name='description',
            field=models.TextField(blank=True, help_text='Description, notes, or agenda for the session'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='room_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the study room', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='session_type',
            field=models.CharField(choices=[('partnership', 'Partnership Session'), ('group', 'Group Session')], default='partnership', help_text='Type of study session', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='title',
            field=models.CharField(default='Study Session', help_text='Title or name of the study session', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studysession',
            name='partnership',
            field=models.ForeignKey(blank=True, help_text='The partnership this session belongs to (for partner sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='community.studypartnership'),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the study group', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the study group's purpose and goals")),
                ('max_members', models.IntegerField(default=6, help_text='Maximum number of members allowed in the group', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)])),
                ('is_public', models.BooleanField(default=True, help_text='Whether the group is publicly visible and joinable')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether new members need approval to join')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', help_text='Current status of the study group', max_length=15)),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of study sessions held by this group', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Student who created this study group', on_delete=django.db.models.deletion.CASCADE, related_name='created_study_groups', to='accounts.studentprofile')),
                ('subject', models.ForeignKey(help_text='Primary subject focus of the study group', on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='community.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='study_group',
            field=models.ForeignKey(blank=True, help_text='The study group this session belongs to (for group sessions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='community.studygroup'),
        ),
        migrations.CreateModel(
            name='StudyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', help_text='Role of the student in the group', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('left', 'Left Group'), ('removed', 'Removed')], default='active', help_text='Current membership status', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='accounts.studentprofile')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.studygroup')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('study_group', 'student')},
            },
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(help_text='Students who are members of this study group', related_name='study_groups', through='community.StudyGroupMembership', to='accounts.studentprofile'),
        ),
        migrations.CreateModel(
            name='StudyGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('file', 'File Share'), ('system', 'System Message')], default='text', max_length=10)),
                ('content', models.TextField(help_text='Message content or system message text')),
                ('file_attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='study_groups/files/')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether the message has been edited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, help_text='Student who sent the message (null for system messages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='accounts.studentprofile')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.studygroup')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyRoomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('inappropriate_behavior', 'Inappropriate Behavior'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('technical_issue', 'Technical Issue'), ('other', 'Other')], help_text='Type of issue being reported', max_length=25)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('moderator_notes', models.TextField(blank=True, help_text='Notes from moderator review')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_room_reports', to='accounts.studentprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.studysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='invited', max_length=15)),
                ('joined_at', models.DateTimeField(blank=True, help_text='When the student joined the session', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When the student left the session', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='community.studysession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.AddField(
            model_name='studysession',
            name='attendees',
            field=models.ManyToManyField(help_text='Students who attended this session', related_name='attended_sessions', through='community.StudySessionAttendance', to='accounts.studentprofile'),
        ),
    ]
