# Generated by Django 5.2.7 on 2025-10-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_add_performance_indexes'),
        ('community', '0002_remove_studysession_notes_studysession_description_and_more'),
    ]

    operations = [
    ]
