# Generated by Django 5.2.7 on 2025-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='leaderboard_visible',
            field=models.BooleanField(default=True, help_text='Whether this student appears on public leaderboards'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='show_real_name',
            field=models.BooleanField(default=False, help_text='Whether to show real name instead of username on leaderboards'),
        ),
    ]
