[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log

[program:django]
command=gunicorn metlab_edu.wsgi:application --bind 127.0.0.1:8000 --workers 4 --worker-class gevent --worker-connections 1000 --max-requests 1000 --max-requests-jitter 100 --timeout 60 --keep-alive 2
directory=/app
user=metlab
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/django.err.log
stdout_logfile=/var/log/supervisor/django.out.log
environment=DJANGO_SETTINGS_MODULE="metlab_edu.settings_production"

[program:daphne]
command=daphne -b 127.0.0.1 -p 8001 metlab_edu.asgi:application
directory=/app
user=metlab
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/daphne.err.log
stdout_logfile=/var/log/supervisor/daphne.out.log
environment=DJANGO_SETTINGS_MODULE="metlab_edu.settings_production"