# Generated by Django 5.0.14 on 2025-12-04 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0003_merge_20251009_1354'),
        ('learning', '0004_merge_20251009_1351'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_type', models.CharField(choices=[('one_on_one', 'One-on-One'), ('group', 'Group Session'), ('class', 'Class Session')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=30)),
                ('allow_screen_share', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_video_sessions', to=settings.AUTH_USER_MODEL)),
                ('teacher_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_sessions', to='learning.teacherclass')),
                ('tutor_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_session', to='community.tutorbooking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_started', 'Session Started'), ('session_ended', 'Session Ended'), ('participant_joined', 'Participant Joined'), ('participant_left', 'Participant Left'), ('screen_share_started', 'Screen Share Started'), ('screen_share_stopped', 'Screen Share Stopped'), ('recording_started', 'Recording Started'), ('recording_stopped', 'Recording Stopped'), ('connection_issue', 'Connection Issue')], max_length=30)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='video_chat.videosession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VideoSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('left', 'Left'), ('removed', 'Removed')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('audio_enabled', models.BooleanField(default=True)),
                ('video_enabled', models.BooleanField(default=True)),
                ('screen_sharing', models.BooleanField(default=False)),
                ('connection_quality', models.CharField(default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='video_chat.videosession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videosession',
            index=models.Index(fields=['session_id'], name='video_chat__session_5ca591_idx'),
        ),
        migrations.AddIndex(
            model_name='videosession',
            index=models.Index(fields=['host', 'status'], name='video_chat__host_id_76c81f_idx'),
        ),
        migrations.AddIndex(
            model_name='videosession',
            index=models.Index(fields=['scheduled_time'], name='video_chat__schedul_dcc8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='videosessionevent',
            index=models.Index(fields=['session', 'event_type'], name='video_chat__session_2ecd85_idx'),
        ),
        migrations.AddIndex(
            model_name='videosessionevent',
            index=models.Index(fields=['timestamp'], name='video_chat__timesta_b90782_idx'),
        ),
        migrations.AddIndex(
            model_name='videosessionparticipant',
            index=models.Index(fields=['session', 'status'], name='video_chat__session_7d3932_idx'),
        ),
        migrations.AddIndex(
            model_name='videosessionparticipant',
            index=models.Index(fields=['user', 'status'], name='video_chat__user_id_70fa39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videosessionparticipant',
            unique_together={('session', 'user')},
        ),
    ]
