# Generated by Django 5.0.14 on 2025-12-05 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate_behavior', 'Inappropriate Behavior'), ('harassment', 'Harassment'), ('bullying', 'Bullying'), ('spam', 'Spam'), ('technical_issue', 'Technical Issue'), ('privacy_violation', 'Privacy Violation'), ('other', 'Other')], help_text='Type of issue being reported', max_length=25)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', help_text='Current status of the report', max_length=15)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the reported issue', max_length=10)),
                ('moderator_notes', models.TextField(blank=True, help_text='Notes from moderator review')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True)),
                ('action_taken', models.TextField(blank=True, help_text='Description of action taken to resolve the issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(blank=True, help_text='User being reported (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_session_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='User who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='video_session_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Moderator who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_video_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Video session being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='video_chat.videosession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='video_chat__session_75abad_idx'), models.Index(fields=['reporter', 'created_at'], name='video_chat__reporte_1b6e68_idx'), models.Index(fields=['reported_user', 'status'], name='video_chat__reporte_32eeb5_idx'), models.Index(fields=['status', 'severity'], name='video_chat__status_d47959_idx')],
            },
        ),
    ]
