# Generated by Django 5.2.7 on 2025-10-08 09:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('quiz', 'Quiz Session'), ('flashcard', 'Flashcard Review'), ('summary', 'Summary Reading'), ('mixed', 'Mixed Learning')], help_text='Type of learning activity in this session', max_length=15)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the learning session started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the learning session ended', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', help_text='Current status of the learning session', max_length=15)),
                ('performance_score', models.FloatField(blank=True, help_text='Performance score as percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('questions_attempted', models.PositiveIntegerField(default=0, help_text='Number of questions attempted in this session')),
                ('questions_correct', models.PositiveIntegerField(default=0, help_text='Number of questions answered correctly')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent in minutes')),
                ('concepts_covered', models.JSONField(default=list, help_text='List of concepts covered in this session')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Difficulty level of the session content', max_length=20)),
                ('xp_earned', models.PositiveIntegerField(default=0, help_text='Experience points earned in this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(help_text='Content used in this learning session', on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='content.uploadedcontent')),
                ('student', models.ForeignKey(help_text='Student who participated in this session', on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Learning Session',
                'verbose_name_plural': 'Learning Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WeaknessAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject area where weakness is identified', max_length=100)),
                ('concept', models.CharField(help_text='Specific concept where student shows weakness', max_length=200)),
                ('weakness_score', models.FloatField(help_text='Weakness score (0-100, higher means more weakness)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('weakness_level', models.CharField(choices=[('low', 'Low Weakness'), ('medium', 'Medium Weakness'), ('high', 'High Weakness'), ('critical', 'Critical Weakness')], help_text='Categorized level of weakness', max_length=15)),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total number of attempts on this concept')),
                ('correct_attempts', models.PositiveIntegerField(default=0, help_text='Number of correct attempts on this concept')),
                ('last_attempt_score', models.FloatField(blank=True, help_text='Score from the most recent attempt', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('improvement_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining'), ('unknown', 'Unknown')], default='unknown', help_text='Trend in performance over time', max_length=20)),
                ('priority_level', models.IntegerField(default=1, help_text='Priority level for addressing this weakness (1-5, 5 is highest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(help_text='Student this weakness analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='weakness_analyses', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Weakness Analysis',
                'verbose_name_plural': 'Weakness Analyses',
                'ordering': ['-priority_level', '-weakness_score'],
                'unique_together': {('student', 'subject', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='PersonalizedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('content', 'Content Recommendation'), ('practice', 'Practice Recommendation'), ('review', 'Review Recommendation'), ('difficulty', 'Difficulty Adjustment'), ('study_plan', 'Study Plan'), ('break', 'Break Suggestion')], help_text='Type of recommendation', max_length=20)),
                ('title', models.CharField(help_text='Title of the recommendation', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the recommendation')),
                ('content', models.JSONField(help_text='Structured data for the recommendation (content IDs, parameters, etc.)')),
                ('priority', models.IntegerField(default=1, help_text='Priority level (1-5, 5 is highest priority)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('completed', 'Completed')], default='pending', help_text='Current status of the recommendation', max_length=15)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=10, help_text='Estimated time to complete this recommendation')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this recommendation expires', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When the student viewed this recommendation', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the student completed this recommendation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_content', models.ForeignKey(blank=True, help_text='Content related to this recommendation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='content.uploadedcontent')),
                ('student', models.ForeignKey(help_text='Student this recommendation is for', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.studentprofile')),
                ('related_weakness', models.ForeignKey(blank=True, help_text='Weakness analysis that triggered this recommendation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='learning.weaknessanalysis')),
            ],
            options={
                'verbose_name': 'Personalized Recommendation',
                'verbose_name_plural': 'Personalized Recommendations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
