# Generated by Django 5.2.7 on 2025-10-08 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(help_text='Date this lesson is scheduled for')),
                ('lesson_type', models.CharField(choices=[('review', 'Review Lesson'), ('new_content', 'New Content'), ('weakness_focus', 'Weakness Focus'), ('mixed', 'Mixed Practice'), ('assessment', 'Assessment')], help_text='Type of lesson content', max_length=20)),
                ('title', models.CharField(help_text='Title of the daily lesson', max_length=200)),
                ('description', models.TextField(help_text='Description of what the lesson covers')),
                ('content_structure', models.JSONField(help_text='Structured lesson content including activities, questions, and materials')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=10, help_text='Estimated time to complete the lesson (5-15 minutes)', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)])),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text="Difficulty level adapted to student's progress", max_length=20)),
                ('priority_concepts', models.JSONField(default=list, help_text='List of key concepts this lesson focuses on')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('expired', 'Expired')], default='scheduled', help_text='Current status of the lesson', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the student started this lesson', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the student completed this lesson', null=True)),
                ('performance_score', models.FloatField(blank=True, help_text="Student's performance score on this lesson", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Actual time spent on the lesson')),
                ('xp_earned', models.PositiveIntegerField(default=0, help_text='Experience points earned from completing this lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_content', models.ManyToManyField(blank=True, help_text='Content materials used in this lesson', related_name='daily_lessons', to='content.uploadedcontent')),
                ('related_weaknesses', models.ManyToManyField(blank=True, help_text='Weaknesses this lesson addresses', related_name='daily_lessons', to='learning.weaknessanalysis')),
                ('student', models.ForeignKey(help_text='Student this lesson is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_lessons', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Daily Lesson',
                'verbose_name_plural': 'Daily Lessons',
                'ordering': ['-lesson_date', '-created_at'],
                'unique_together': {('student', 'lesson_date')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('quiz', 'Quiz Question'), ('flashcard', 'Flashcard Review'), ('reading', 'Reading Activity'), ('practice', 'Practice Exercise'), ('reflection', 'Reflection Question')], help_text='Type of activity completed', max_length=15)),
                ('activity_index', models.PositiveIntegerField(help_text='Index of the activity within the lesson')),
                ('concept', models.CharField(help_text='Concept covered in this activity', max_length=200)),
                ('question_text', models.TextField(blank=True, help_text='Text of the question or activity prompt')),
                ('student_answer', models.TextField(blank=True, help_text="Student's answer or response")),
                ('correct_answer', models.TextField(blank=True, help_text='Correct answer for the activity')),
                ('is_correct', models.BooleanField(blank=True, help_text="Whether the student's answer was correct", null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on this specific activity')),
                ('difficulty_rating', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text="Student's perceived difficulty of this activity", max_length=10)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(help_text='Lesson this progress entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='learning.dailylesson')),
            ],
            options={
                'verbose_name': 'Lesson Progress',
                'verbose_name_plural': 'Lesson Progress Entries',
                'ordering': ['lesson', 'activity_index'],
                'unique_together': {('lesson', 'activity_index')},
            },
        ),
    ]
