# Generated by Django 5.2.7 on 2025-10-08 16:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_leaderboard_visible_and_more'),
        ('content', '0001_initial'),
        ('learning', '0002_dailylesson_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the class', max_length=200)),
                ('subject', models.CharField(help_text='Subject taught in this class', max_length=100)),
                ('grade_level', models.CharField(help_text='Grade level for this class', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the class')),
                ('invitation_code', models.CharField(help_text='Unique code for students to join the class', max_length=8, unique=True)),
                ('max_students', models.PositiveIntegerField(default=30, help_text='Maximum number of students allowed in this class', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the class is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Teacher who created this class', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher Class',
                'verbose_name_plural': 'Teacher Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the content', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the content')),
                ('subject', models.CharField(help_text='Subject this content covers', max_length=100)),
                ('grade_level', models.CharField(help_text='Appropriate grade level for this content', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this content is available to all students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_classes', models.ManyToManyField(blank=True, help_text='Classes this content is assigned to', related_name='assigned_content', to='learning.teacherclass')),
                ('teacher', models.ForeignKey(help_text='Teacher who uploaded this content', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_content', to='accounts.teacherprofile')),
                ('uploaded_content', models.OneToOneField(help_text='The uploaded content file', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_content', to='content.uploadedcontent')),
            ],
            options={
                'verbose_name': 'Teacher Content',
                'verbose_name_plural': 'Teacher Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customized_questions', models.JSONField(help_text='Customized quiz questions with teacher modifications')),
                ('title', models.CharField(help_text='Custom title for the quiz', max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for students')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Time limit for the quiz in minutes', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('attempts_allowed', models.PositiveIntegerField(default=1, help_text='Number of attempts allowed per student', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the quiz is currently available to students')),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for quiz completion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_classes', models.ManyToManyField(blank=True, help_text='Classes this quiz is assigned to', related_name='assigned_quizzes', to='learning.teacherclass')),
                ('generated_quiz', models.ForeignKey(help_text='The AI-generated quiz this is based on', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_customizations', to='content.generatedquiz')),
                ('teacher', models.ForeignKey(help_text='Teacher who created/customized this quiz', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_quizzes', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher Quiz',
                'verbose_name_plural': 'Teacher Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the enrollment is currently active')),
                ('student', models.ForeignKey(help_text='Student enrolled in the class', on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='accounts.studentprofile')),
                ('teacher_class', models.ForeignKey(help_text='Class the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.teacherclass')),
            ],
            options={
                'verbose_name': 'Class Enrollment',
                'verbose_name_plural': 'Class Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('teacher_class', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='Which attempt this is for the student')),
                ('answers', models.JSONField(help_text="Student's answers to the quiz questions")),
                ('score', models.FloatField(help_text='Score achieved on this attempt (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('time_taken_minutes', models.PositiveIntegerField(help_text='Time taken to complete the quiz in minutes')),
                ('started_at', models.DateTimeField(help_text='When the student started this attempt')),
                ('completed_at', models.DateTimeField(help_text='When the student completed this attempt')),
                ('student', models.ForeignKey(help_text='Student who made this attempt', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='accounts.studentprofile')),
                ('quiz', models.ForeignKey(help_text='Quiz this attempt is for', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.teacherquiz')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-completed_at'],
                'unique_together': {('quiz', 'student', 'attempt_number')},
            },
        ),
    ]
