# Generated by Django 5.2.7 on 2025-10-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_add_performance_indexes'),
        ('learning', '0003_teacherclass_teachercontent_teacherquiz_and_more'),
    ]

    operations = [
    ]
