# Generated by Django 5.2.7 on 2025-10-08 07:10

import content.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded content file', upload_to=content.models.content_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'pptx']), content.models.validate_file_size])),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text File'), ('image', 'Image File'), ('pptx', 'PowerPoint Presentation')], help_text='Type of content uploaded', max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status', max_length=15)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when processing was completed', null=True)),
                ('key_concepts', models.JSONField(blank=True, help_text='AI-extracted key concepts from the content', null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text content from the file')),
                ('subject', models.CharField(blank=True, help_text='Subject/topic of the content', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', help_text='Difficulty level of the content', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who uploaded the content', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Content',
                'verbose_name_plural': 'Uploaded Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the quiz', max_length=200)),
                ('questions', models.JSONField(help_text='JSON array of quiz questions with answers and options')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level of the quiz', max_length=10)),
                ('question_count', models.PositiveIntegerField(default=0, help_text='Number of questions in the quiz')),
                ('estimated_time_minutes', models.PositiveIntegerField(default=10, help_text='Estimated time to complete the quiz in minutes', validators=[django.core.validators.MaxValueValidator(120)])),
                ('topics_covered', models.JSONField(default=list, help_text='List of topics/concepts covered in the quiz')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(help_text='Content this quiz was generated from', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.uploadedcontent')),
            ],
            options={
                'verbose_name': 'Generated Quiz',
                'verbose_name_plural': 'Generated Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.TextField(help_text='Text displayed on the front of the flashcard (question/term)')),
                ('back_text', models.TextField(help_text='Text displayed on the back of the flashcard (answer/definition)')),
                ('concept_tag', models.CharField(help_text='Tag identifying the concept this flashcard covers', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty level of the flashcard', max_length=10)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order of this flashcard within the content set')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(help_text='Content this flashcard was generated from', on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='content.uploadedcontent')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['content', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('short', 'Short Summary'), ('medium', 'Medium Summary'), ('detailed', 'Detailed Summary')], help_text='Type/length of the summary', max_length=10)),
                ('text', models.TextField(help_text='Generated summary text')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Number of words in the summary')),
                ('key_points', models.JSONField(default=list, help_text='List of key points covered in the summary')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(help_text='Content this summary was generated from', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='content.uploadedcontent')),
            ],
            options={
                'verbose_name': 'Generated Summary',
                'verbose_name_plural': 'Generated Summaries',
                'unique_together': {('content', 'summary_type')},
            },
        ),
    ]
