# Generated by Django 5.2.7 on 2025-10-08 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the achievement', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of how to earn this achievement')),
                ('badge_icon', models.CharField(help_text='Icon identifier for the achievement badge', max_length=50)),
                ('achievement_type', models.CharField(choices=[('streak', 'Learning Streak'), ('xp', 'Experience Points'), ('lesson', 'Lesson Completion'), ('quiz', 'Quiz Performance'), ('subject', 'Subject Mastery'), ('social', 'Social Interaction'), ('special', 'Special Event')], help_text='Category of achievement', max_length=20)),
                ('xp_requirement', models.IntegerField(default=0, help_text='XP points required to unlock this achievement', validators=[django.core.validators.MinValueValidator(0)])),
                ('streak_requirement', models.IntegerField(default=0, help_text='Streak days required to unlock this achievement', validators=[django.core.validators.MinValueValidator(0)])),
                ('lesson_requirement', models.IntegerField(default=0, help_text='Number of lessons required to unlock this achievement', validators=[django.core.validators.MinValueValidator(0)])),
                ('xp_reward', models.IntegerField(default=0, help_text='XP points awarded when achievement is earned', validators=[django.core.validators.MinValueValidator(0)])),
                ('coin_reward', models.IntegerField(default=0, help_text='Virtual coins awarded when achievement is earned', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this achievement is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['achievement_type', 'xp_requirement'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent'), ('bonus', 'Bonus'), ('refund', 'Refund')], help_text='Type of coin transaction', max_length=20)),
                ('amount', models.IntegerField(help_text='Amount of coins in transaction', validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(help_text='Reason for the transaction', max_length=200)),
                ('balance_after', models.IntegerField(help_text='Coin balance after this transaction', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Coin Transaction',
                'verbose_name_plural': 'Coin Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0, help_text='Current coin balance', validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_today', models.IntegerField(default=0, help_text='Coins earned today', validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_this_week', models.IntegerField(default=0, help_text='Coins earned this week', validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_this_month', models.IntegerField(default=0, help_text='Coins earned this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_earned', models.IntegerField(default=0, help_text='Total coins earned all time', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_spent', models.IntegerField(default=0, help_text='Total coins spent all time', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_currency', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Virtual Currency',
                'verbose_name_plural': 'Virtual Currencies',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('lesson_complete', 'Lesson Completion'), ('quiz_score', 'Quiz Performance'), ('streak_bonus', 'Streak Bonus'), ('achievement', 'Achievement Reward'), ('daily_goal', 'Daily Goal'), ('perfect_score', 'Perfect Score Bonus'), ('improvement', 'Improvement Bonus')], help_text='Source of XP earning', max_length=20)),
                ('base_xp', models.IntegerField(help_text='Base XP amount before multipliers', validators=[django.core.validators.MinValueValidator(0)])),
                ('multiplier', models.FloatField(default=1.0, help_text='Multiplier applied to base XP', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)])),
                ('final_xp', models.IntegerField(help_text='Final XP amount after multipliers', validators=[django.core.validators.MinValueValidator(0)])),
                ('streak_bonus', models.IntegerField(default=0, help_text='Additional XP from streak bonus', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(help_text='Description of XP earning activity', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'XP Transaction',
                'verbose_name_plural': 'XP Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time'), ('subject', 'Subject Specific')], help_text='Type of leaderboard ranking', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject for subject-specific leaderboards', max_length=100)),
                ('weekly_xp', models.IntegerField(default=0, help_text='XP earned this week', validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_xp', models.IntegerField(default=0, help_text='XP earned this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('all_time_xp', models.IntegerField(default=0, help_text='Total XP earned all time', validators=[django.core.validators.MinValueValidator(0)])),
                ('rank', models.IntegerField(default=0, help_text='Current rank position', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['rank'],
                'unique_together': {('student', 'leaderboard_type', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False, help_text='Whether the student has been notified of this achievement')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='gamification.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Achievement',
                'verbose_name_plural': 'Student Achievements',
                'ordering': ['-earned_at'],
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
