# Generated by Django 5.2.7 on 2025-10-08 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_leaderboard_visible_and_more'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the shop item', max_length=100)),
                ('description', models.TextField(help_text='Description of what the item does')),
                ('item_type', models.CharField(choices=[('theme', 'Dashboard Theme'), ('hint', 'Quiz Hint'), ('customization', 'Profile Customization'), ('power_up', 'Learning Power-up'), ('avatar', 'Avatar Item'), ('badge', 'Special Badge')], help_text='Category of shop item', max_length=20)),
                ('price', models.IntegerField(help_text='Price in coins', validators=[django.core.validators.MinValueValidator(1)])),
                ('icon', models.CharField(help_text='Icon identifier for the item', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is available for purchase')),
                ('is_limited', models.BooleanField(default=False, help_text='Whether this is a limited-time item')),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Available stock (null for unlimited)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('level_requirement', models.IntegerField(default=1, help_text='Minimum student level required to purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Item',
                'verbose_name_plural': 'Shop Items',
                'ordering': ['item_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity purchased', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.IntegerField(help_text='Total price paid in coins', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', help_text='Status of the purchase', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.studentprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='gamification.shopitem')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity owned (for consumable items)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=False, help_text='Whether this item is currently active/equipped')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='gamification.shopitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Inventory',
                'verbose_name_plural': 'Student Inventories',
                'ordering': ['-purchased_at'],
                'unique_together': {('student', 'item')},
            },
        ),
    ]
