# Generated by Django 5.2.7 on 2025-10-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_add_performance_indexes'),
        ('gamification', '0002_shopitem_purchase_studentinventory'),
    ]

    operations = [
    ]
